### ISSUE TITLE
Non-blocking dialogs

### ISSUE THREAD

**Issue by danielpeintner** [jpro-one/jpro-issues#1]
In your documentation checklist you clearly state that blocking showAndWait() et cetera are not to be used.

Do you have some good practice what to use instead of JavaFX dialogs. In Controlsfx there used to be [non-blocking lightweight dialogs](http://fxexperience.com/controlsfx/features/dialogs/) but these haven been deprecated  and removed.

Any good advice or tip would be useful!

**Comment by FlorianKirmaier** [comment]
Thank you for the feedback.

There is a simple pattern for this problem.
You can add a StackPane to the root of the scene, which can be used to display "popups" of the application.
When the popup is closed, it has to remove itself from the StackPane

I will keep this ticket open, until the documentation is extended regarding that topic.
We will probably also write a small utility-library for that issue.

**Comment by FlorianKirmaier** [comment]
@danielpeintner 
I added a new project, which contains various samples.
It contains a sample about dialoges.

https://github.com/jpro-one/JPro-Samples

**Comment by FlorianKirmaier** [comment]
@usfchlih 
there is an example about filehandling in the samples-project:
https://github.com/jpro-one/jpro-samples
