### ISSUE TITLE
Draw problem with MediaViews

### ISSUE THREAD

**Issue by rvictor89** [jpro-one/jpro-issues#3]
If a MediaView is added to a container, for example in the center of a Borderpane and in this center further controls are contained, for example buttons, then the entire container is no longer drawn correctly, in this case the center of the Borderpane.

**Comment by FlorianKirmaier** [comment]
@rvictor89 
Thank you for the report. I tried to reproduce the problem, but i wasn't able to to do so.

I tried to reproduce the bug with the following code-snippet:

```java
    @Override
    public void start(Stage stage) throws Exception{

        BorderPane border = new BorderPane();

        Media media = new Media(getClass().getResource("/test/BunnyShort.mp4").toURI().toString());
        MediaPlayer player = new MediaPlayer(media);

        Button button = new Button("switch");
        button.setOnAction((e) -> {
            StackPane s = new StackPane(new MediaView(player));
            s.setStyle("-fx-background-color: yellow;");
            border.setCenter(s);
        });
        border.setLeft(new HBox(new Button("123"),new Button("456")));
        border.setBottom(button);
        player.play();

        stage.setScene(new Scene(border, 600,600));
        stage.show();
    }
```
I also tried some other variations.
Can you give me further hints, on how to reproduce that bug?

Please note, that the MediaView is not rendered in JPRO.
But using the MediaView shouldn't influence any of the other components.

**Comment by rvictor89** [comment]
See this simple snippet:

```java
@Override
    public void start(Stage stage)
    {
        HBox hBox = new HBox();
        Button button1 = new Button("Button1");
        Button button2 = new Button("Button2");
        Button button3 = new Button("Button3");
        MediaView mediaView = new MediaView();
        hBox.getChildren().addAll(button1, button2, button3, mediaView);

        stage.setScene(new Scene(hBox));
        stage.show();
    }
```

This snippet can't be renderd at all, but if i don't add the mediaview to the hbox then the three button will be renderd correctly.

**Comment by rvictor89** [comment]
Interestingly, if you put the MediaView into another container and then add it to the HBox instead, then everything is displayed correctly again. Apparently only the container in which the MediaView is inside is affected.

See this snippet:

```java
@Override
    public void start(Stage stage) {
        HBox hBox = new HBox();
        Button button1 = new Button("Button1");
        Button button2 = new Button("Button2");
        Button button3 = new Button("Button3");
        MediaView mediaView = new MediaView();
        HBox innerBox = new HBox();
        innerBox.getChildren().add(mediaView);
        hBox.getChildren().addAll(button1, button2, button3, innerBox);

        stage.setScene(new Scene(hBox));
        stage.show();
    }
```

**Comment by FlorianKirmaier** [comment]
Thanks for the more detailed example.
Can you try out the version `2018.1.4-SNAPSHOT`?
It should fix the rendering-problem.

**Comment by rvictor89** [comment]
It works, thank you ;)
